FROM node:20.11.1-alpine3.19 AS build
# Setting up the work directory
WORKDIR /app
# Installing dependencies
COPY ./package*.json ./
RUN npm install
ENV PATH=/app/node_modules/.bin:$PATH
COPY . .
CMD ["npm", "run", "dev"]