upstream frontend{
    server frontend:3000;
}

upstream auth{
    server auth:5000;
}

upstream task{
    server task:8000;
}


server {
    listen 80;

    server_name localhost;

    location /api/auth/ {
        # if ($request_method = 'OPTIONS') {
        #     add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
        #     add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        #     add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, x-auth-token' always;
        #     add_header 'Access-Control-Allow-Credentials' 'true' always;
        #     return 204;
        # }

        proxy_pass http://auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
        # add_header 'Access-Control-Allow-Credentials' 'true' always;
    }

    location /api/task/ {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, x-auth-token' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            return 204;
        }
        proxy_pass http://task/api/todos/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;

    }

    location /api/label/ {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, x-auth-token' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            return 204;
        }
        proxy_pass http://task/api/labels/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;

    }

    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
