upstream frontend{
    server frontend:3000;
}

upstream auth{
    server auth:5000;
}

upstream task{
    server task:8000;
}


server {
    listen 80;
    server_name localhost;

    # server react frontend
    location / {
        proxy_pass http://frontend;
    }

    # backend - user authentication service
    location /api/auth/ {
        proxy_pass http://auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS, PATCH";
        add_header Access-Control-Allow-Headers "Authorization, Content-Type";
    }

    location /api/task/ {
        proxy_pass http://task/todos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS, PATCH";
        add_header Access-Control-Allow-Headers "Authorization, Content-Type";
    }

    location /api/label/ {
        proxy_pass http://task/labels;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS, PATCH";
        add_header Access-Control-Allow-Headers "Authorization, Content-Type";
    }

    # error_page 404 /index.html;
}
