spring.application.name=user
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://user-db:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

jwt.secret="JDOyB5htvM+8Pk9+Q8ylM1DbKNz95YiYwI9j5ZyA7e8="
jwt.expiration=259200000
server.port=5000